import type { Metadata } from 'next';
import { AuthLayout } from '@template/presentation/layouts/auth-layout';

export const metadata: Metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default AuthLayout;
