import type { Metadata } from 'next';
import { DashboardLayout } from '@template/presentation/layouts/dashboard-layout';

export const metadata: Metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default DashboardLayout;
